// Frontend products mirroring backend schema exactly
export const PRODUCTS = [
  { id: 1, name: 'Protein Energy Bar Chocolate', category: 'Food', brand: 'NutriFit', price: 45, description: 'Chocolate flavored protein snack bar for quick energy.', features: '12g protein, low sugar, ready to eat', tags: 'snack protein gym healthy chocolate', attributes_json: {calories:210, veg:true, expiry:'6 months'} },
  { id: 2, name: 'Whole Wheat Bread', category: 'Food', brand: 'FarmFresh', price: 40, description: 'Soft whole wheat bread for breakfast and sandwiches.', features: 'High fiber, preservative free', tags: 'bread breakfast healthy wheat', attributes_json: {calories:120, veg:true, expiry:'4 days'} },
  { id: 3, name: 'Greek Yogurt Natural', category: 'Food', brand: 'MilkyDay', price: 85, description: 'Thick probiotic yogurt good for digestion.', features: 'High protein, low fat', tags: 'yogurt probiotic breakfast diet', attributes_json: {calories:95, veg:true, protein_high:true, expiry:'10 days'} },
  { id: 4, name: 'Spicy Chicken Momos', category: 'Food', brand: 'TastyBites', price: 120, description: 'Frozen chicken momos with spicy filling.', features: 'Ready to steam, juicy taste', tags: 'nonveg snack frozen spicy', attributes_json: {calories:300, veg:false, expiry:'3 months'} },
  { id: 5, name: 'Veg Sandwich Pack', category: 'Food', brand: 'QuickEats', price: 60, description: 'Fresh vegetable sandwich pack for lunch.', features: 'Tomato, cucumber, mayo filling', tags: 'veg sandwich snack lunch', attributes_json: {calories:180, veg:true, expiry:'2 days'} },
  { id: 6, name: 'Peanut Butter Crunchy', category: 'Food', brand: 'NutriSpread', price: 180, description: 'Crunchy peanut butter rich in protein.', features: 'No added sugar, roasted peanuts', tags: 'spread protein breakfast gym', attributes_json: {calories:588, veg:true, expiry:'8 months'} },
  { id: 7, name: 'Oats Breakfast Mix', category: 'Food', brand: 'HealthStart', price: 150, description: 'Instant oats for healthy breakfast meals.', features: 'High fiber, quick cooking', tags: 'oats healthy diet fiber', attributes_json: {calories:150, veg:true, expiry:'9 months'} },
  { id: 8, name: 'Cheese Slices', category: 'Food', brand: 'DailyDairy', price: 110, description: 'Creamy cheese slices for sandwiches and burgers.', features: 'Calcium rich, fresh dairy', tags: 'cheese dairy sandwich burger', attributes_json: {calories:90, veg:true, expiry:'20 days'} },
  { id: 9, name: 'Brown Eggs Pack 12', category: 'Food', brand: 'FarmNest', price: 95, description: 'Farm fresh protein rich eggs.', features: 'Grade A eggs, hygienic packing', tags: 'eggs protein breakfast nonveg', attributes_json: {calories:70, veg:false, expiry:'15 days'} },
  { id: 10, name: 'Paneer Fresh 200g', category: 'Food', brand: 'MilkyDay', price: 90, description: 'Soft cottage cheese ideal for cooking.', features: 'Fresh milk, high protein', tags: 'paneer vegetarian protein cooking', attributes_json: {calories:265, veg:true, expiry:'7 days'} },
  { id: 11, name: 'Veg Noodles Cup', category: 'Food', brand: 'SnackTime', price: 35, description: 'Instant vegetable noodles cup.', features: 'Ready in 3 minutes', tags: 'noodles instant snack quick', attributes_json: {calories:320, veg:true, expiry:'6 months'} },
  { id: 12, name: 'Chocolate Muffin', category: 'Food', brand: 'BakeHouse', price: 30, description: 'Soft baked chocolate muffin dessert.', features: 'Freshly baked, sweet treat', tags: 'cake muffin dessert chocolate', attributes_json: {calories:260, veg:true, expiry:'3 days'} },
  { id: 13, name: 'Cornflakes Classic', category: 'Food', brand: 'MorningCrunch', price: 210, description: 'Crispy cornflakes cereal for breakfast.', features: 'Iron fortified, crunchy flakes', tags: 'cereal breakfast healthy kids', attributes_json: {calories:110, veg:true, expiry:'10 months'} },
  { id: 14, name: 'Apple Juice 1L', category: 'Food', brand: 'FruitPure', price: 99, description: 'Fresh apple juice with no added sugar.', features: 'Natural fruit extract', tags: 'juice drink healthy fruit', attributes_json: {calories:45, veg:true, expiry:'6 months'} },
  { id: 15, name: 'Banana Chips Salted', category: 'Food', brand: 'Snacky', price: 55, description: 'Crispy salted banana chips snack.', features: 'Deep fried crunchy slices', tags: 'chips snack salty tea-time', attributes_json: {calories:540, veg:true, expiry:'5 months'} },
  { id: 16, name: 'Veg Salad Bowl', category: 'Food', brand: 'FreshBowl', price: 70, description: 'Mixed vegetable salad for healthy meals.', features: 'Low calorie, fiber rich', tags: 'salad healthy diet lowcalorie', attributes_json: {calories:80, veg:true, expiry:'1 day'} },
  { id: 17, name: 'Chicken Sausage Pack', category: 'Food', brand: 'MeatMaster', price: 160, description: 'Smoked chicken sausages rich in protein.', features: 'Ready to fry or grill', tags: 'sausage nonveg protein snack', attributes_json: {calories:250, veg:false, expiry:'2 months'} },
  { id: 18, name: 'Butter Cookies', category: 'Food', brand: 'SweetTreats', price: 120, description: 'Crunchy butter cookies for tea time.', features: 'Fresh bakery style cookies', tags: 'cookies biscuit sweet snack', attributes_json: {calories:500, veg:true, expiry:'4 months'} },
  { id: 19, name: 'Milk Chocolate Bar', category: 'Food', brand: 'ChocoLove', price: 50, description: 'Creamy milk chocolate bar.', features: 'Smooth cocoa blend', tags: 'chocolate dessert sweet', attributes_json: {calories:230, veg:true, expiry:'12 months'} },
  { id: 20, name: 'Protein Shake Vanilla', category: 'Food', brand: 'NutriFit', price: 95, description: 'Ready to drink vanilla protein shake.', features: '20g protein, low fat', tags: 'protein drink gym shake fitness', attributes_json: {calories:160, veg:true, expiry:'5 months'} },

  { id: 21, name: 'Basmati Rice 5kg', category: 'Groceries', brand: 'NatureFarm', price: 649, description: 'Premium long grain aromatic rice.', features: 'Aged rice, easy cooking', tags: 'rice staple organic healthy', attributes_json: {weight:'5kg', organic:true} },
  { id: 22, name: 'Toor Dal 1kg', category: 'Groceries', brand: 'DailyChoice', price: 189, description: 'Protein rich split pigeon peas.', features: 'Natural and clean pulses', tags: 'dal protein pulses vegetarian', attributes_json: {weight:'1kg'} },
  { id: 23, name: 'Sunflower Oil 1L', category: 'Groceries', brand: 'FreshHarvest', price: 159, description: 'Refined cooking oil for daily use.', features: 'Low cholesterol oil', tags: 'oil cooking healthy refined', attributes_json: {volume:'1L'} },
  { id: 24, name: 'Wheat Flour Atta 5kg', category: 'Groceries', brand: 'GrainGold', price: 280, description: 'Stone ground whole wheat flour.', features: 'Soft rotis and chapatis', tags: 'atta flour wheat cooking', attributes_json: {weight:'5kg'} },
  { id: 25, name: 'Sugar White 1kg', category: 'Groceries', brand: 'SweetPure', price: 45, description: 'Refined white sugar crystals.', features: 'Fine granules', tags: 'sugar sweet baking cooking', attributes_json: {weight:'1kg'} },
  { id: 26, name: 'Salt Iodized 1kg', category: 'Groceries', brand: 'HealthSalt', price: 20, description: 'Iodized table salt.', features: 'Essential minerals', tags: 'salt cooking daily essential', attributes_json: {weight:'1kg'} },
  { id: 27, name: 'Tea Powder Premium', category: 'Groceries', brand: 'ChaiKing', price: 210, description: 'Strong flavored black tea leaves.', features: 'Rich aroma', tags: 'tea beverage chai drink', attributes_json: {weight:'500g'} },
  { id: 28, name: 'Coffee Instant 200g', category: 'Groceries', brand: 'WakeUp', price: 175, description: 'Instant coffee granules.', features: 'Strong caffeine kick', tags: 'coffee instant beverage energy', attributes_json: {weight:'200g'} },
  { id: 29, name: 'Detergent Powder 2kg', category: 'Groceries', brand: 'PureLife', price: 299, description: 'Deep cleaning detergent.', features: 'Machine wash safe', tags: 'detergent cleaning laundry', attributes_json: {weight:'2kg'} },
  { id: 30, name: 'Dishwash Liquid 500ml', category: 'Groceries', brand: 'CleanMate', price: 85, description: 'Liquid dish cleaner.', features: 'Grease removal formula', tags: 'dishwash cleaning kitchen', attributes_json: {volume:'500ml'} },
  { id: 31, name: 'Bath Soap Pack 4', category: 'Groceries', brand: 'FreshGlow', price: 120, description: 'Moisturizing bathing soap.', features: 'Aloe vera extract', tags: 'soap hygiene personalcare', attributes_json: {quantity:4} },
  { id: 32, name: 'Toilet Cleaner 1L', category: 'Groceries', brand: 'CleanMate', price: 99, description: 'Strong disinfectant cleaner.', features: 'Kills germs fast', tags: 'cleaner disinfectant hygiene', attributes_json: {volume:'1L'} },
  { id: 33, name: 'Turmeric Powder 200g', category: 'Groceries', brand: 'SpiceWorld', price: 40, description: 'Pure turmeric powder.', features: 'Natural spice', tags: 'turmeric spice cooking indian', attributes_json: {weight:'200g'} },
  { id: 34, name: 'Chilli Powder 200g', category: 'Groceries', brand: 'SpiceWorld', price: 50, description: 'Red chilli powder for spicy dishes.', features: 'Fine ground spice', tags: 'chilli spice hot cooking', attributes_json: {weight:'200g'} },
  { id: 35, name: 'Jeera Cumin 100g', category: 'Groceries', brand: 'SpiceWorld', price: 35, description: 'Whole cumin seeds for seasoning.', features: 'Fresh aroma', tags: 'cumin spice seasoning', attributes_json: {weight:'100g'} },
  { id: 36, name: 'Tomato Ketchup 1kg', category: 'Groceries', brand: 'TastySauce', price: 110, description: 'Sweet and tangy tomato ketchup.', features: 'Kids favorite sauce', tags: 'ketchup sauce snack', attributes_json: {weight:'1kg'} },
  { id: 37, name: 'Biscuits Marie Pack', category: 'Groceries', brand: 'TeaTime', price: 25, description: 'Light tea biscuits.', features: 'Low sugar', tags: 'biscuit snack tea light', attributes_json: {weight:'150g'} },
  { id: 38, name: 'Paper Towels Roll', category: 'Groceries', brand: 'CleanHome', price: 60, description: 'Absorbent kitchen paper towels.', features: 'Multi purpose cleaning', tags: 'tissue cleaning kitchen', attributes_json: {quantity:1} },
  { id: 39, name: 'Garbage Bags Large', category: 'Groceries', brand: 'CleanHome', price: 95, description: 'Durable trash bags for home use.', features: 'Leak proof plastic', tags: 'garbage trash bags waste', attributes_json: {quantity:20} },
  { id: 40, name: 'Mineral Water 2L', category: 'Groceries', brand: 'PureDrop', price: 35, description: 'Safe drinking mineral water.', features: 'Filtered and hygienic', tags: 'water drinking bottle', attributes_json: {volume:'2L'} },

  { id: 41, name: 'AstraBook Pro 15 Laptop', category: 'Electronic Gadgets', brand: 'Astra', price: 58999, description: 'Gaming laptop for students and developers.', features: '16GB RAM, RTX GPU, SSD', tags: 'gaming laptop coding performance', attributes_json: {ram:'16GB', battery:'6 hours'} },
  { id: 42, name: 'Smartphone Nova X', category: 'Electronic Gadgets', brand: 'NovaTech', price: 19999, description: 'Budget smartphone with long battery life.', features: '6GB RAM, 6000mAh battery', tags: 'mobile phone battery budget', attributes_json: {battery:'6000mAh', storage:'128GB'} },
  { id: 43, name: 'Bluetooth Earbuds AirTune', category: 'Electronic Gadgets', brand: 'Sonic', price: 2499, description: 'Wireless earbuds with deep bass.', features: 'Touch controls, noise isolation', tags: 'earbuds music wireless', attributes_json: {battery:'24 hours'} },
  { id: 44, name: 'Smartwatch FitTrack', category: 'Electronic Gadgets', brand: 'FitTech', price: 3499, description: 'Fitness smartwatch with heart rate tracking.', features: 'Steps, sleep monitor, waterproof', tags: 'watch fitness health tracker', attributes_json: {battery:'7 days'} },
  { id: 45, name: 'Power Bank 10000mAh', category: 'Electronic Gadgets', brand: 'VoltMax', price: 999, description: 'Portable charging power bank.', features: 'Fast charging dual output', tags: 'powerbank battery travel', attributes_json: {battery:'10000mAh'} },
  { id: 46, name: 'Gaming Mouse RGB', category: 'Electronic Gadgets', brand: 'GamePro', price: 1299, description: 'High precision gaming mouse.', features: 'RGB lights adjustable DPI', tags: 'mouse gaming accessory', attributes_json: {dpi:'12000'} },
  { id: 47, name: 'Mechanical Keyboard', category: 'Electronic Gadgets', brand: 'KeyMaster', price: 3499, description: 'Mechanical keyboard for typing and gaming.', features: 'Blue switches backlit', tags: 'keyboard mechanical gaming', attributes_json: {switch:'blue'} },
  { id: 48, name: 'LED Monitor 24inch', category: 'Electronic Gadgets', brand: 'VisionX', price: 7999, description: 'Full HD LED computer monitor.', features: '75Hz refresh rate', tags: 'monitor display hd office', attributes_json: {size:'24 inch'} },
  { id: 49, name: 'USB Flash Drive 64GB', category: 'Electronic Gadgets', brand: 'DataSafe', price: 599, description: 'Portable USB storage drive.', features: 'High speed transfer', tags: 'pendrive storage portable', attributes_json: {capacity:'64GB'} },
  { id: 50, name: 'External Hard Disk 1TB', category: 'Electronic Gadgets', brand: 'DataSafe', price: 3899, description: 'Backup and storage device.', features: 'USB 3.0 fast speed', tags: 'harddisk storage backup', attributes_json: {capacity:'1TB'} },
  { id: 51, name: 'WiFi Router Dual Band', category: 'Electronic Gadgets', brand: 'NetLink', price: 2499, description: 'High speed home router.', features: 'Dual band 5GHz', tags: 'router wifi internet', attributes_json: {speed:'1200Mbps'} },
  { id: 52, name: 'Portable Speaker Boom', category: 'Electronic Gadgets', brand: 'Sonic', price: 1999, description: 'Loud portable bluetooth speaker.', features: 'Deep bass waterproof', tags: 'speaker music party', attributes_json: {battery:'10 hours'} },
  { id: 53, name: 'Webcam HD Pro', category: 'Electronic Gadgets', brand: 'VisionX', price: 1599, description: 'HD webcam for online meetings.', features: '1080p video mic built-in', tags: 'webcam office meetings', attributes_json: {resolution:'1080p'} },
  { id: 54, name: 'Tablet Lite 10', category: 'Electronic Gadgets', brand: 'NovaTech', price: 13999, description: 'Lightweight tablet for study and entertainment.', features: '10 inch display 4GB RAM', tags: 'tablet study media', attributes_json: {battery:'8 hours'} },
  { id: 55, name: 'Tripod Stand Pro', category: 'Electronic Gadgets', brand: 'CaptureIt', price: 899, description: 'Stable tripod for camera or phone.', features: 'Adjustable height', tags: 'tripod camera stand vlog', attributes_json: {height:'150cm'} },
  { id: 56, name: 'Portable SSD 512GB', category: 'Electronic Gadgets', brand: 'DataSafe', price: 5599, description: 'High speed portable SSD.', features: 'Ultra fast data transfer', tags: 'ssd storage portable fast', attributes_json: {capacity:'512GB'} },
  { id: 57, name: 'Hair Dryer Turbo', category: 'Electronic Gadgets', brand: 'StylePro', price: 1499, description: 'Quick drying hair dryer.', features: 'Hot and cool air modes', tags: 'hairdryer grooming appliance', attributes_json: {power:'1200W'} },
  { id: 58, name: 'Electric Kettle 1.5L', category: 'Electronic Gadgets', brand: 'HomeEase', price: 999, description: 'Fast boiling electric kettle.', features: 'Auto cut off stainless steel', tags: 'kettle kitchen boiling', attributes_json: {capacity:'1.5L'} },
  { id: 59, name: 'Extension Board 6 Socket', category: 'Electronic Gadgets', brand: 'SafePlug', price: 499, description: 'Multi socket power extension board.', features: 'Surge protection', tags: 'extension power safety', attributes_json: {sockets:6} },
  { id: 60, name: 'Mini Projector BeamLite', category: 'Electronic Gadgets', brand: 'VisionX', price: 6999, description: 'Compact home theater projector.', features: 'HD projection HDMI support', tags: 'projector movie portable', attributes_json: {resolution:'720p'} }
]

// Ensure every product has an availability field (mocked on frontend)
PRODUCTS.forEach(p => {
  if (p.availability === undefined) {
    if (p.category === 'Food') p.availability = 5 + (p.id % 16) // 5-20
    else if (p.category === 'Groceries') p.availability = 20 + (p.id % 81) // 20-100
    else if (p.category === 'Electronic Gadgets') p.availability = 3 + (p.id % 8) // 3-10
    else p.availability = 10
  }
})

// Simple fetcher that mimics an API call and returns a promise
export function fetchProducts(){
  return new Promise((resolve)=>{
    setTimeout(()=>resolve(PRODUCTS), 300)
  })
}
